/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as WhatWeDoIndexRouteImport } from './routes/what-we-do.index'
import { Route as WhatWeDoSlugRouteImport } from './routes/what-we-do.$slug'
import { Route as WhoWeAreIndexRouteImport } from './routes/who-we-are.index'
import { Route as WhoWeAreApproachRouteImport } from './routes/who-we-are.approach'
import { Route as WhoWeAreEcosystemRouteImport } from './routes/who-we-are.ecosystem'
import { Route as WhoWeAreOurPeopleRouteImport } from './routes/who-we-are.our-people'
import { Route as WhoWeAreWhyHarakaRouteImport } from './routes/who-we-are.why-haraka'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoIndexRoute = WhatWeDoIndexRouteImport.update({
  id: '/what-we-do/',
  path: '/what-we-do/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoSlugRoute = WhatWeDoSlugRouteImport.update({
  id: '/what-we-do/$slug',
  path: '/what-we-do/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreIndexRoute = WhoWeAreIndexRouteImport.update({
  id: '/who-we-are/',
  path: '/who-we-are/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreApproachRoute = WhoWeAreApproachRouteImport.update({
  id: '/who-we-are/approach',
  path: '/who-we-are/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreEcosystemRoute = WhoWeAreEcosystemRouteImport.update({
  id: '/who-we-are/ecosystem',
  path: '/who-we-are/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreOurPeopleRoute = WhoWeAreOurPeopleRouteImport.update({
  id: '/who-we-are/our-people',
  path: '/who-we-are/our-people',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreWhyHarakaRoute = WhoWeAreWhyHarakaRouteImport.update({
  id: '/who-we-are/why-haraka',
  path: '/who-we-are/why-haraka',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/$': typeof AdminSplatRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/what-we-do/$slug': typeof WhatWeDoSlugRoute
  '/who-we-are/approach': typeof WhoWeAreApproachRoute
  '/who-we-are/ecosystem': typeof WhoWeAreEcosystemRoute
  '/who-we-are/our-people': typeof WhoWeAreOurPeopleRoute
  '/who-we-are/why-haraka': typeof WhoWeAreWhyHarakaRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/what-we-do/': typeof WhatWeDoIndexRoute
  '/who-we-are/': typeof WhoWeAreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/$': typeof AdminSplatRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/what-we-do/$slug': typeof WhatWeDoSlugRoute
  '/who-we-are/approach': typeof WhoWeAreApproachRoute
  '/who-we-are/ecosystem': typeof WhoWeAreEcosystemRoute
  '/who-we-are/our-people': typeof WhoWeAreOurPeopleRoute
  '/who-we-are/why-haraka': typeof WhoWeAreWhyHarakaRoute
  '/solutions': typeof SolutionsIndexRoute
  '/what-we-do': typeof WhatWeDoIndexRoute
  '/who-we-are': typeof WhoWeAreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/$': typeof AdminSplatRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/what-we-do/$slug': typeof WhatWeDoSlugRoute
  '/who-we-are/approach': typeof WhoWeAreApproachRoute
  '/who-we-are/ecosystem': typeof WhoWeAreEcosystemRoute
  '/who-we-are/our-people': typeof WhoWeAreOurPeopleRoute
  '/who-we-are/why-haraka': typeof WhoWeAreWhyHarakaRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/what-we-do/': typeof WhatWeDoIndexRoute
  '/who-we-are/': typeof WhoWeAreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/insights'
    | '/privacy'
    | '/products'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/$'
    | '/solutions/$slug'
    | '/what-we-do/$slug'
    | '/who-we-are/approach'
    | '/who-we-are/ecosystem'
    | '/who-we-are/our-people'
    | '/who-we-are/why-haraka'
    | '/solutions/'
    | '/what-we-do/'
    | '/who-we-are/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/insights'
    | '/privacy'
    | '/products'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/$'
    | '/solutions/$slug'
    | '/what-we-do/$slug'
    | '/who-we-are/approach'
    | '/who-we-are/ecosystem'
    | '/who-we-are/our-people'
    | '/who-we-are/why-haraka'
    | '/solutions'
    | '/what-we-do'
    | '/who-we-are'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/insights'
    | '/privacy'
    | '/products'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/$'
    | '/solutions/$slug'
    | '/what-we-do/$slug'
    | '/who-we-are/approach'
    | '/who-we-are/ecosystem'
    | '/who-we-are/our-people'
    | '/who-we-are/why-haraka'
    | '/solutions/'
    | '/what-we-do/'
    | '/who-we-are/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  InsightsRoute: typeof InsightsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  WhatWeDoSlugRoute: typeof WhatWeDoSlugRoute
  WhoWeAreApproachRoute: typeof WhoWeAreApproachRoute
  WhoWeAreEcosystemRoute: typeof WhoWeAreEcosystemRoute
  WhoWeAreOurPeopleRoute: typeof WhoWeAreOurPeopleRoute
  WhoWeAreWhyHarakaRoute: typeof WhoWeAreWhyHarakaRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
  WhatWeDoIndexRoute: typeof WhatWeDoIndexRoute
  WhoWeAreIndexRoute: typeof WhoWeAreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/': {
      id: '/what-we-do/'
      path: '/what-we-do'
      fullPath: '/what-we-do/'
      preLoaderRoute: typeof WhatWeDoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do/$slug': {
      id: '/what-we-do/$slug'
      path: '/what-we-do/$slug'
      fullPath: '/what-we-do/$slug'
      preLoaderRoute: typeof WhatWeDoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are/': {
      id: '/who-we-are/'
      path: '/who-we-are'
      fullPath: '/who-we-are/'
      preLoaderRoute: typeof WhoWeAreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are/approach': {
      id: '/who-we-are/approach'
      path: '/who-we-are/approach'
      fullPath: '/who-we-are/approach'
      preLoaderRoute: typeof WhoWeAreApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are/ecosystem': {
      id: '/who-we-are/ecosystem'
      path: '/who-we-are/ecosystem'
      fullPath: '/who-we-are/ecosystem'
      preLoaderRoute: typeof WhoWeAreEcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are/our-people': {
      id: '/who-we-are/our-people'
      path: '/who-we-are/our-people'
      fullPath: '/who-we-are/our-people'
      preLoaderRoute: typeof WhoWeAreOurPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are/why-haraka': {
      id: '/who-we-are/why-haraka'
      path: '/who-we-are/why-haraka'
      fullPath: '/who-we-are/why-haraka'
      preLoaderRoute: typeof WhoWeAreWhyHarakaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  InsightsRoute: InsightsRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  WhatWeDoSlugRoute: WhatWeDoSlugRoute,
  WhoWeAreApproachRoute: WhoWeAreApproachRoute,
  WhoWeAreEcosystemRoute: WhoWeAreEcosystemRoute,
  WhoWeAreOurPeopleRoute: WhoWeAreOurPeopleRoute,
  WhoWeAreWhyHarakaRoute: WhoWeAreWhyHarakaRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
  WhatWeDoIndexRoute: WhatWeDoIndexRoute,
  WhoWeAreIndexRoute: WhoWeAreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
